-- AlterTable
ALTER TABLE "Club" ALTER COLUMN "Address" DROP NOT NULL,
ALTER COLUMN "City" DROP NOT NULL,
ALTER COLUMN "Country" DROP NOT NULL,
ALTER COLUMN "ZipCode" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "clubID" DROP NOT NULL,
ALTER COLUMN "clubIDRequest" DROP NOT NULL;
